POST https://tap-api-v2.proofpoint.com/v2/url/decode
Content-Type: application/json

{
    "urls": [
        "https://urldefense.com/v3/__https://picsum.photos/id/65/400/300__;!!PUxuPyJo!xMPbze75LRKpcxrAU6IDcCUek89k41P_mNqMw5cXRtlMi2qibLulibnx-9BEjc8aaUeK45_iH08buUQUbZjqAbmdjCm_1SI$ ",
        "https://urldefense.com/v3/__https://picsum.photos/id/96/400/300__;!!PUxuPyJo!xMPbze75LRKpcxrAU6IDcCUek89k41P_mNqMw5cXRtlMi2qibLulibnx-9BEjc8aaUeK45_iH08buUQUbZjqAbmdiZOfn7E$ "

    ]
}

POST http://localhost:3000/api/decode
Content-Type: application/json

{
    "urls": [
        "https://urldefense.com/v3/__https://picsum.photos/id/65/400/300__;!!PUxuPyJo!xMPbze75LRKpcxrAU6IDcCUek89k41P_mNqMw5cXRtlMi2qibLulibnx-9BEjc8aaUeK45_iH08buUQUbZjqAbmdjCm_1SI$ ",
        "https://urldefense.com/v3/__https://picsum.photos/id/96/400/300__;!!PUxuPyJo!xMPbze75LRKpcxrAU6IDcCUek89k41P_mNqMw5cXRtlMi2qibLulibnx-9BEjc8aaUeK45_iH08buUQUbZjqAbmdiZOfn7E$ "

    ]
}